// screens/fieldKeys.js
export const fieldKeys = [
  'batuk_lebih_2_minggu',
  'demam',
  'keringat_malam',
  'sesak_nafas',
  'nyeri_dada',
  'benjolan',
  'batuk_berdarah',
  'batuk_kurang_2_minggu',
  'nafsu_makan_turun',
  'mudah_lelah',
  'bb_turun',
  'serumah_sakit_tbc',
  'satu_ruangan_tbc',
  'serumah_dengan_tbc',
  'tbc_tuntas',
  'tbc_tidak_tuntas',
  'diabetes',
  'hiv',
  'ibu_hamil',
  'merokok',
  'usia_0_14',
  'lansia',
];
